//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RizaWpfEditor {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RizaWpfEditor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Asset Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssetBrowser {
            get {
                return ResourceManager.GetString("AssetBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build(_B) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_arrow_minimize_vertical_24_regular-custom.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Arrow_Minimize_Vertical_Custom {
            get {
                return ResourceManager.GetString("Icon_Arrow_Minimize_Vertical_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_dismiss_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Dismiss {
            get {
                return ResourceManager.GetString("Icon_Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_full_screen_maximize_24_regular.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_FullScreen_Maximize {
            get {
                return ResourceManager.GetString("Icon_FullScreen_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_full_screen_minimize_24_regular.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_FullScreen_Minimize {
            get {
                return ResourceManager.GetString("Icon_FullScreen_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_library_128_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Library {
            get {
                return ResourceManager.GetString("Icon_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ic_fluent_save_128_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Save {
            get {
                return ResourceManager.GetString("Icon_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window(_W) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
