//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RizaWpfEditor {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RizaWpfEditor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display(_D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game(_G) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_album_add_128_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Add_Project {
            get {
                return ResourceManager.GetString("Icon-Add-Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_arrow_minimize_vertical_24_regular.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Arrow_Minimize_Vertical {
            get {
                return ResourceManager.GetString("Icon-Arrow-Minimize-Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_arrow_minimize_vertical_24_regular-custom.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Arrow_Minimize_Vertical_Custom {
            get {
                return ResourceManager.GetString("Icon-Arrow-Minimize-Vertical-Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_dismiss_24_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Dismiss {
            get {
                return ResourceManager.GetString("Icon-Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_folder_open_128_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_FolderOpen {
            get {
                return ResourceManager.GetString("Icon-FolderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_full_screen_maximize_24_regular.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_FullScreen_Maximize {
            get {
                return ResourceManager.GetString("Icon-FullScreen-Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_full_screen_minimize_24_regular.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_FullScreen_Minimize {
            get {
                return ResourceManager.GetString("Icon-FullScreen-Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_library_128_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Library {
            get {
                return ResourceManager.GetString("Icon-Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_open_128_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Open {
            get {
                return ResourceManager.GetString("Icon-Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_pause_128_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Pause {
            get {
                return ResourceManager.GetString("Icon-Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_play_128_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Play {
            get {
                return ResourceManager.GetString("Icon-Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_arrow_redo_128_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Redo {
            get {
                return ResourceManager.GetString("Icon-Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_save_128_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Save {
            get {
                return ResourceManager.GetString("Icon-Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_stop_128_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Stop {
            get {
                return ResourceManager.GetString("Icon-Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /RizaWpfEditor;component/Icons/ic_fluent_arrow_undo_128_filled.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Undo {
            get {
                return ResourceManager.GetString("Icon-Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Project... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Template に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
    }
}
